# -*- coding: utf-8 -*-
"""Calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMULCqtuEZ6hI_6RDayF985IQfbWNc3b
"""

#Code to make a simple calculator with basic arithemetic operations.

def calculator():
  print("Simple Calculator")
  print("Select operation:")
  print("1. Add(+)")
  print("2. Subtract(-)")
  print("3. Multilply(*)")
  print("4. Divide(/)")


  #Get user input
  num1 = float(input("Enter first number: "))
  num2 = float(input("Enter second number: "))
  operation = input("Enter operation (+, -, *, /): ")

  #Perform calculation
  if operation == '+':
    result = num1 + num2
    print("Result: ",result)
  elif operation == '-':
    result = num1 - num2
    print("Result: ",result)
  elif operation == '*':
    result = num1 * num2
    print("Resut: ",result)
  elif operation == '/':
    if num2 != 0:
      result = num1 / num2
      print("Result: ",result)
    else:
      print("Error: Division by zero is not allowed.")
  else:
    print("Invalid Operation")

#Run the calculator
calculator()