# -*- coding: utf-8 -*-
"""Contact_Book

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqgPGyWPvH7NdcmUQUeaQN-kjPpM7lni
"""

# Contact Book in Python

contacts = {}

def add_contact():
    name = input("Enter Name: ").strip()
    phone = input("Enter Phone Number: ").strip()
    email = input("Enter Email: ").strip()
    address = input("Enter Address: ").strip()

    contacts[name] = {
        "Phone": phone,
        "Email": email,
        "Address": address
    }
    print("Contact added successfully.\n")

def view_contacts():
    if not contacts:
        print("No contacts found.\n")
        return
    for name, info in contacts.items():
        print(f"\nName: {name}")
        print(f"Phone: {info['Phone']}")
        print(f"Email: {info['Email']}")
        print(f"Address: {info['Address']}")
    print()

def search_contact():
    query = input("Enter name or phone number to search: ").strip()
    found = False
    for name, info in contacts.items():
        if query.lower() in name.lower() or query in info['Phone']:
            print(f"\nFound Contact - Name: {name}")
            print(f"Phone: {info['Phone']}")
            print(f"Email: {info['Email']}")
            print(f"Address: {info['Address']}")
            found = True
    if not found:
        print("No contact found with that name or number.\n")

def update_contact():
    name = input("Enter the name of the contact to update: ").strip()
    if name in contacts:
        print("Leave the field empty if you don't want to change it.")
        phone = input("New Phone Number: ").strip()
        email = input("New Email: ").strip()
        address = input("New Address: ").strip()

        if phone:
            contacts[name]['Phone'] = phone
        if email:
            contacts[name]['Email'] = email
        if address:
            contacts[name]['Address'] = address
        print("Contact updated successfully.\n")
    else:
        print("Contact not found.\n")

def delete_contact():
    name = input("Enter the name of the contact to delete: ").strip()
    if name in contacts:
        del contacts[name]
        print("Contact deleted successfully.\n")
    else:
        print("Contact not found.\n")

def contact_book():
    while True:
        print("\n--- Contact Book Menu ---")
        print("1. Add Contact")
        print("2. View Contact List")
        print("3. Search Contact")
        print("4. Update Contact")
        print("5. Delete Contact")
        print("6. Exit")

        choice = input("Enter your choice (1-6): ").strip()

        if choice == '1':
            add_contact()
        elif choice == '2':
            view_contacts()
        elif choice == '3':
            search_contact()
        elif choice == '4':
            update_contact()
        elif choice == '5':
            delete_contact()
        elif choice == '6':
            print("Thank you for using the Contact Book.")
            break
        else:
            print("Invalid choice. Please try again.\n")

if __name__ == "__main__":
    contact_book()