# -*- coding: utf-8 -*-
"""Rock-Paper-Scissor  Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opqJfIUMeb1Ebcjw_RDSnfpwVvLIIXvd
"""

import random
def get_computer_choice():
  return random.choice(['rock','paper','scissors'])
def get_user_choice():
  choice = input("Enter your choice (rock,paper,scissors): ").lower()
  while choice not in ['rock','paper','scissors']:
    print("Invalid choice.Try again.")
    choice = input("Enter your choice (rock,paper,scissors): ").lower()
  return choice
def determine_winner(user, computer):
  if user == computer:
    return "tie"
  elif (user == "rock" and computer == "scissors") or \
       (user == "scissors" and computer == "paper") or \
       (user == "paper" and computer == "rock"):
       return "user"
  else:
    return "computer"
def play_game():
  user_score = 0
  computer_score = 0
  while True:
    user_choice = get_user_choice()
    computer_choice = get_computer_choice()
    print(f"You chose: {user_choice}")
    print(f"Computer chose: {computer_choice}")
    winner = determine_winner(user_choice, computer_choice)
    if winner == "user":
      user_score += 1
      print("You win this round!")
    elif winner == "computer":
      computer_score += 1
      print("Computer wins this round!")
    else:
      print("It's a tie!")
    print(f"Score => You: {user_score} | Computer: {computer_score}")
    play_again = input("Do you want to play again? (yes/no): ").lower()
    if play_again != 'yes':
      break
  print("Thanks for playing!")
if __name__ == "__main__":
  play_game()